# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BDP_Parse2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import *
from PyQt5.QtWidgets import *
from PyQt5.QtWidgets import QLabel
from PyQt5.QtCore import *
from PyQt5.QtGui import *


class ComboBox(QComboBox):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.previous = ""
        self.current = "OLxxx"


class ListBoxWidget(QListWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.links = set()
        self.setAcceptDrops(True)
        self.setGeometry(QtCore.QRect(400, 400, 200, 200))

    def dragEnterEvent(self, event):
        if event.mimeData().hasUrls:
            event.accept()
        else:
            event.ignore()

    def dragMoveEvent(self, event):
        if event.mimeData().hasUrls():
            event.setDropAction(Qt.CopyAction)
            event.accept()
        else:
            event.ignore()

    def dropEvent(self, event):
        if event.mimeData().hasUrls():
            event.setDropAction(Qt.CopyAction)
            event.accept()
            for url in event.mimeData().urls():
                item = QtWidgets.QListWidgetItem()
                font = QtGui.QFont()
                font.setPointSize(10)
                item.setFont(font)
                if (url.isLocalFile()) and (str(url.toLocalFile()) not in self.links):
                    self.links.add(str(url.toLocalFile()))
                    item.setText(str(url.toLocalFile()))
                    self.addItem(item)
        else:
            event.ignore()

     
class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        MainWindow.setAcceptDrops(True)
        MainWindow.setStyleSheet("background-color: #1F1F1F;")
        MainWindow.setWindowIcon(QtGui.QIcon("icon/binary-file.png"))
        # MainWindow.setWindowFlags(Qt.FramelessWindowHint)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setStyleSheet("background-color: #2C2C2C;"
                                      "selection-background-color: #03DAC6;"
                                      "border-style:outset;"
                                      "border-radius:5px;"
                                      "border: 1px solid;"
                                      "border-color: #673AB7;"
                                      "color: #d9d9d9;"
                                      "padding:8px;")
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)

        item = QtWidgets.QListWidgetItem()
        item.setFont(font)
        self.listWidget.addItem(item)
        self.listWidget.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.listWidget.itemPressed["QListWidgetItem*"].connect(
            lambda item: item.setCheckState(
                Qt.Checked
                if item.checkState() == Qt.Unchecked
                else Qt.Unchecked
            )
        )
        self.listWidget.setSpacing(8)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        # item.setEnabled(False)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        item.setFont(font)
        self.listWidget.addItem(item)

        # self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        # self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget.setObjectName("listwidget")

        self.listWidget.horizontalScrollBar().setStyleSheet("QScrollBar"
                                                            "{"
                                                            "height:8px;"
                                                            "background:solid white;"
                                                            "border-radius:0px;"
                                                            "}"
                                                            "QScrollBar::handle"
                                                            "{"
                                                            "background:#673AB7;"
                                                            "border-radius:5px;"
                                                            "height:5px"
                                                            "}"
                                                            "QScrollBar::add-line:horizontal"
                                                            "{"
                                                            "border:none;"
                                                            "background:none;"
                                                            "color:none;"
                                                            "}"
                                                            "QScrollBar::sub-line:horizontal"
                                                            "{"
                                                            "border:none;"
                                                            "background:none;"
                                                            "color:none;"
                                                            "}"
                                                            )

        self.listWidget.verticalScrollBar().setStyleSheet("QScrollBar"
                                                          "{"
                                                          "width:5px;"
                                                          "background:transparent;"
                                                          "border-radius:50px;"
                                                          "}"
                                                          "QScrollBar::handle"
                                                          "{"
                                                          "background : #C38FFF;"
                                                          "border-radius:10px;"
                                                          "}"
                                                          "QScrollBar::add-line:vertical"
                                                          "{"
                                                          "border:none;"
                                                          "background:none;"
                                                          "color:none;"
                                                          "}"
                                                          "QScrollBar::sub-line:vertical"
                                                          "{"
                                                          "border:none;"
                                                          "background:none;"
                                                          "color:none;"
                                                          "}"
                                                          )

        self.gridLayout.addWidget(self.listWidget, 2, 4, 4, 3)

        # Drop down combo button
        self.drop_down = QtWidgets.QListView(self.centralwidget)
        self.drop_down.setStyleSheet("color: #D9D9D9;"
                                     "background-color: #2C2C2C;"
                                     "border : 0px solid;"
                                    #  "border-radius:1px;"
                                    #  "border-color: #673AB7;"
                                     )
        self.CB_SKUSelect = ComboBox(self.centralwidget)
        self.CB_SKUSelect.setView(self.drop_down)
        font.setPointSize(12)
        self.CB_SKUSelect.setFont(font)
        self.drop_down.setFont(font)
        self.CB_SKUSelect.setStyleSheet("QComboBox"
                                        "{"
                                        "color: #D9D9D9;"
                                        "border : 1px solid;"
                                        "border-radius:5px;"
                                        "border-color: #673AB7;"
                                        "padding-left:10px;"
                                        "background-color: #2C2C2C;"
                                        "}"
                                        "QComboBox::drop-down"
                                        "{"
                                        "border-width:10px;"
                                        "}"
                                        "QComboBox::focus"
                                        "{"
                                        "color: #FF6F00;"
                                        "}"
                                        "QComboBox::down-arrow"
                                        "{"
                                        "image: url(icon/drop-down.png);"
                                        "border : 0px solid;"
                                        "border-radius:0px;"
                                        "border-color: #1E1E1E;"
                                        "width:22px;"
                                        "height:25px;"
                                        "border-width-right:20px;"
                                        "}"
                                        )
        self.CB_SKUSelect.setObjectName("CB_SKUSelect")
        self.CB_SKUSelect.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.CB_SKUSelect.addItem("")
        self.CB_SKUSelect.addItem("")
        # self.CB_SKUSelect.currentTextChanged.connect(self.comboboxChanged)
        self.CB_SKUSelect.setFixedHeight(60)
        self.gridLayout.addWidget(self.CB_SKUSelect, 1, 1, 1, 3)

        # Push Button
        self.PB_File = QtWidgets.QPushButton(self.centralwidget)
        font.setPointSize(14)
        self.PB_File.setFont(font)
        self.PB_File.setStyleSheet("background-color: #673AB7;"
                                   "border-style:outset;"
                                   # "border : 2px solid;"
                                   # "border-color: #C38FFF;"
                                   "color: #D9D9D9;"
                                   "height:30px;"
                                   "padding-top: 10px;"
                                   "padding-bottom: 10px;"
                                   "padding-left: 10px;"
                                   "padding-right: 10px;"
                                   "border-radius:10px;")
        self.PB_File.setObjectName("PB_File")
        self.PB_File.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        # self.PB_File.setIcon(QIcon("icon/paperclip.png"))

        self.gridLayout.addWidget(self.PB_File, 7, 1, 1, 1)

        self.PB_Parse = QtWidgets.QPushButton(self.centralwidget)
        font.setPointSize(14)
        self.PB_Parse.setFont(font)
        self.PB_Parse.setStyleSheet("background-color: #673AB7;"
                                    "border-style:outset;"
                                    "color: #D9D9D9;"
                                    "border-radius:10px;"
                                    "height:30px;"
                                    "padding-top: 10px;"
                                    "padding-bottom: 10px;"
                                    "padding-left: 10px;"
                                    "padding-right: 10px;"
                                    )
        self.PB_Parse.setObjectName("PB_Parse")
        self.PB_Parse.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.gridLayout.addWidget(self.PB_Parse, 7, 2, 1, 2)

        self.PB_Clear = QtWidgets.QPushButton(self.centralwidget)
        font.setPointSize(14)
        self.PB_Clear.setFont(font)
        self.PB_Clear.setStyleSheet("background-color: #673AB7;"
                                    "border-style:outset;"
                                    "color: #D9D9D9;"
                                    "border-radius:10px;"
                                    # "border : 2px solid;"
                                    # "border-color: #03DAC6;"
                                    "height:30px;"
                                    "padding-top: 10px;"
                                    "padding-bottom: 10px;"
                                    "padding-left: 10px;"
                                    "padding-right: 10px;"
                                    )
        self.PB_Clear.setObjectName("PB_Clear")
        self.PB_Clear.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.gridLayout.addWidget(self.PB_Clear, 7, 4, 1, 2)

        self.PB_Quit = QtWidgets.QPushButton(self.centralwidget)
        font.setPointSize(14)
        self.PB_Quit.setFont(font)
        self.PB_Quit.setStyleSheet("background-color: #D0112B;"
                                   "border-style:outset;"
                                   "color: #D9D9D9;"
                                   "height:30px;"
                                   # "border : 5px solid;"
                                   # "border-color: #D0112B;"
                                   "padding-top: 10px;"
                                   "padding-bottom: 10px;"
                                   "padding-left: 10px;"
                                   "padding-right: 10px;"
                                   "border-radius:20px;"
                                   )
        self.PB_Quit.setObjectName("PB_Quit")
        self.PB_Quit.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.gridLayout.addWidget(self.PB_Quit, 7, 6, 1, 1)

        self.Text_drop = ListBoxWidget(self.centralwidget)
        self.Text_drop.setStyleSheet("background-color: #2C2C2C;"
                                     "selection-background-color: #3700B3;"
                                     "border-style:outset;"
                                     "border-radius:5px;"
                                     "border: 1px solid;"
                                     "border-color: #673AB7;"
                                     "color: #d9d9d9;"
                                     "padding:8px;")
        self.Text_drop.setObjectName("Text_drop")
        self.Text_drop.horizontalScrollBar().setStyleSheet("QScrollBar"
                                                           "{"
                                                           "height:8px;"
                                                           "background:#673AB7;"
                                                           "border-radius:0px;"
                                                           "}"
                                                           "QScrollBar::handle"
                                                           "{"
                                                           "background:#000000;"
                                                           "border-radius:0px;"
                                                           "width:5px"
                                                           "}"
                                                           "QScrollBar::add-line:horizontal"
                                                           "{"
                                                           "border:none;"
                                                           "background:none;"
                                                           "color:none;"
                                                           "}"
                                                           "QScrollBar::sub-line:horizontal"
                                                           "{"
                                                           "border:none;"
                                                           "background:none;"
                                                           "color:none;"
                                                           "}"
                                                           )
        self.Text_drop.verticalScrollBar().setStyleSheet("QScrollBar"
                                                         "{"
                                                         "width:5px;"
                                                         "background:transparent;"
                                                         "border-radius:50px;"
                                                         "}"
                                                         "QScrollBar::handle"
                                                         "{"
                                                         "background : #C38FFF;"
                                                         "border-radius:10px;"
                                                         "}"
                                                         "QScrollBar::add-line:vertical"
                                                         "{"
                                                         "border:none;"
                                                         "background:none;"
                                                         "color:none;"
                                                         "}"
                                                         "QScrollBar::sub-line:vertical"
                                                         "{"
                                                         "border:none;"
                                                         "background:none;"
                                                         "color:none;"
                                                         "}"
                                                         )
        item = QtWidgets.QListWidgetItem()
        self.Text_drop.addItem(item)
        self.gridLayout.addWidget(self.Text_drop, 2, 1, 2, 3)

        self.Text_status = ListBoxWidget(self.centralwidget)
        self.Text_status.setStyleSheet("background-color: #2C2C2C;"
                                       "border-style:outset;"
                                       "border-radius:5px;"
                                       "border: 1px solid;"
                                       "border-color: #673AB7;"
                                       "color: #d9d9d9;"
                                       "padding:8px;")
        self.Text_status.setObjectName("Text_status")
        item = QtWidgets.QListWidgetItem()
        self.Text_status.addItem(item)
        self.gridLayout.addWidget(self.Text_status, 4, 1, 2, 3)

        self.info_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.info_label.setText("© Ninja Testing")
        self.info_label.setFont(font)
        self.info_label.setAlignment(QtCore.Qt.AlignRight)
        self.info_label.setStyleSheet("color: #d9d9d9;")
        self.gridLayout.addWidget(self.info_label, 1, 4, 1, 3)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        return self

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Parser Application"))
        item = self.listWidget.item(0)
        item.setText("Parameters: ")
        item.setFlags(Qt.NoItemFlags)
        item = self.listWidget.item(1)
        item.setText("Software version (WZ)")
        item.setFlags(Qt.NoItemFlags)
        item = self.listWidget.item(2)
        item.setText("Heatsink (KN1)")
        item = self.listWidget.item(3)
        item.setText("AF NTC (KN2)")
        item = self.listWidget.item(4)
        item.setText("PC NTC (KN3)")
        item = self.listWidget.item(5)
        item.setText("Probe1 NTC (KN4)")
        item = self.listWidget.item(6)
        item.setText("Probe2 NTC (KN5)")
        item = self.listWidget.item(7)
        item.setText("Low Pressure Switch (SW1)")
        item = self.listWidget.item(8)
        item.setText("High Pressure Switch (SW2)")

        # self.CB_8.setText(
        #     _translate("MainWindow", "New Placeholder for checking scrolling. What happens if I write a paragraph"))
        # self.CB_9.setText(
        #     _translate("MainWindow", "New Placeholder for checking scrolling. What happens if I write a paragraph"))
        # self.CB_10.setText(
        #     _translate("MainWindow", "New Placeholder for checking scrolling. What happens if I write a paragraph"))
        # self.CB_11.setText(
        #     _translate("MainWindow", "New Placeholder for checking scrolling. What happens if I write a paragraph"))

        self.PB_File.setText(_translate("MainWindow", "Add File"))
        self.PB_Quit.setText(_translate("MainWindow", "Quit"))
        self.PB_Clear.setText(_translate("MainWindow", "Clear"))
        self.PB_Parse.setText(_translate("MainWindow", "Parse"))
        self.CB_SKUSelect.setItemText(0, _translate("MainWindow", "OLxxx"))
        self.CB_SKUSelect.setItemText(1, _translate("MainWindow", "CFPxxx"))
        __sortingEnabled = self.Text_drop.isSortingEnabled()
        self.Text_drop.setSortingEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        item = self.Text_drop.item(0)
        item.setFont(font)
        item.setText(_translate("MainWindow", "Drop Files Here:"))
        self.Text_drop.setSortingEnabled(__sortingEnabled)

        self.Text_status.setSortingEnabled(False)
        item = self.Text_status.item(0)
        item.setFont(font)
        item.setText(_translate("MainWindow", "Status:"))
        self.Text_status.setSortingEnabled(__sortingEnabled)

    